*&---------------------------------------------------------------------*
*&  Include           ZASSETRAK_CONTROLLER_SEL
*&---------------------------------------------------------------------*
SELECTION-SCREEN BEGIN OF BLOCK b0 WITH FRAME TITLE text-000.

PARAMETERS pr_exp RADIOBUTTON GROUP rg0  USER-COMMAND rdo DEFAULT 'X'.


SELECTION-SCREEN BEGIN OF BLOCK b1 WITH FRAME TITLE text-001.

PARAMETERS p_mdata AS CHECKBOX MODIF ID exp DEFAULT 'X'.
PARAMETERS p_cdata AS CHECKBOX MODIF ID exp DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK b1.


SELECTION-SCREEN BEGIN OF BLOCK b2 WITH FRAME TITLE text-002.

PARAMETERS p_adata AS CHECKBOX MODIF ID exp DEFAULT 'X'.

SELECT-OPTIONS s_bukrs FOR gv_bukrs MODIF ID exp NO-EXTENSION NO INTERVALS.
*SELECT-OPTIONS s_werks FOR gv_werks MODIF ID exp .
SELECT-OPTIONS s_afabe FOR gv_afabe MODIF ID exp OBLIGATORY DEFAULT '01' NO-EXTENSION NO INTERVALS.
*SELECT-OPTIONS s_gjahr FOR gv_gjahr MODIF ID exp OBLIGATORY DEFAULT sy-datum NO-EXTENSION NO INTERVALS.
*select-OPTIONS s_date for gv_date.

PARAMETERS pr_all RADIOBUTTON GROUP rg1 MODIF ID exp.
PARAMETERS pr_delta RADIOBUTTON GROUP rg1 DEFAULT 'X' MODIF ID exp.
* asset value full download
PARAMETERS pr_aval RADIOBUTTON GROUP rg1 MODIF ID exp.
PARAMETERS cu_dwld RADIOBUTTON GROUP rg1 MODIF ID exp.
     select-OPTIONS s_date for gv_date MODIF ID exp.

SELECTION-SCREEN END OF BLOCK b2.
* import
PARAMETERS pr_imp RADIOBUTTON GROUP rg0.

SELECTION-SCREEN BEGIN OF BLOCK b3 WITH FRAME TITLE text-003.

PARAMETERS p_import AS CHECKBOX MODIF ID imp DEFAULT 'X'.

SELECTION-SCREEN END OF BLOCK b3.

* review
PARAMETERS pr_rev RADIOBUTTON GROUP rg0.

* asset send rejected values
PARAMETERS pr_arej RADIOBUTTON GROUP rg0.


SELECTION-SCREEN END OF BLOCK b0.
